---
- name: initial.yml | Include OS-specific variables.
  include_vars: "vars-{{ ansible_os_family }}.yml"

# Update the server
- name: initial.yml | Updating Server
  apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    purge: true
