---
- name: Converge
  hosts: all
  gather_facts: false

  vars:
    ci_build_testing: true

  pre_tasks:

    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

    - name: Gather facts after Python is definitely present.
      setup:

  roles:
    - ubzyhd.nginx
